#!/bin/sh

if [ -z "$1" ]
then
	echo "incorrect '\$1' - aborting ..."
	exit 1
fi

source /var/packages/autorun/target/config
TRIES=20
LOGDIR="/var/packages/autorun/target"
MOUNTPATH=""
COUNT=0

echo "`date +%Y-%m-%d` `date +%H:%M:%S`: device '$1' - inserted, trying to find mount point<br/>" >> $LOGDIR/log

while ([ -z "$MOUNTPATH" ] && [ $COUNT -lt $TRIES ])
do
	MOUNTPATH=`/bin/mount 2>&1 | /bin/grep "/dev/$1" | /usr/bin/cut -d ' ' -f3`
	COUNT=$(($COUNT+1))
	/bin/sleep 1s
done

if [ -z "$MOUNTPATH" ]
then
	echo "`date +%Y-%m-%d` `date +%H:%M:%S`: device '$1' - unable to find mount point, aborting<br/>" >> $LOGDIR/log
	exit 1
fi

echo "`date +%Y-%m-%d` `date +%H:%M:%S`: device '$1' - mount point '$MOUNTPATH' found<br/>" >> $LOGDIR/log

if [ -x "$MOUNTPATH/$SCRIPT" ]
then
	echo "`date +%Y-%m-%d` `date +%H:%M:%S`: device '$1' - script '$MOUNTPATH/$SCRIPT' found, executing<br/>" >> $LOGDIR/log
	if [ $BEEP = "1" ]
	then
	    echo 2 > /dev/ttyS1
	fi
	if [ $LED = "1" ]
	then
		echo : > /dev/ttyS1
	fi
	$MOUNTPATH/$SCRIPT $MOUNTPATH $1
	RESULT=$?
        FREE=`/bin/df -h "$MOUNTPATH" | /bin/grep "$MOUNTPATH" | /usr/bin/awk '{ print $4 }'`
	if [ $RESULT = "100" ]
	then
		echo "`date +%Y-%m-%d` `date +%H:%M:%S`: device '$1' - script '$MOUNTPATH/$SCRIPT' finished ($FREE left on device), starting unmount<br/>" >> $LOGDIR/log
		sleep 5
		sync
		umount $MOUNTPATH
		if [ $? -eq 0 ]
		then
			echo 1 > /sys/block/$1/device/delete
			echo "`date +%Y-%m-%d` `date +%H:%M:%S`: device '$1' - unmounted and ejected<br/>" >> $LOGDIR/log
		else
			echo "`date +%Y-%m-%d` `date +%H:%M:%S`: device '$1' - <span style=\"color:red;\">error while unmounting '$MOUNTPATH', aborting</span><br/>" >> $LOGDIR/log
			echo 3 > /dev/ttyS1
			sleep 1s
			echo 3 > /dev/ttyS1
			sleep 1s
			echo 3 > /dev/ttyS1
			exit 1
		fi
	else
		echo "`date +%Y-%m-%d` `date +%H:%M:%S`: device '$1' - script '$MOUNTPATH/$SCRIPT' finished ($FREE left on device), no further actions<br/>" >> $LOGDIR/log
	fi
	if [ $BEEP = "1" ]
	then
		echo 2 > /dev/ttyS1
	fi
	if [ $LED = "1" ]
	then
		echo 8 > /dev/ttyS1
	fi
        if [ $NOTIFY = "1" ]
        then
		/usr/syno/bin/synodsmnotify $NOTIFYTARGET "autorun" "script finished, $FREE left on $MOUNTPATH"
        fi
else
	echo "`date +%Y-%m-%d` `date +%H:%M:%S`: device '$1' - no script '$MOUNTPATH/$SCRIPT' found, no further actions<br/>" >> $LOGDIR/log
fi

exit 0
