#!/bin/sh

if [ -d "/tmp/net.reidemeister.autorun" ]
then
    # restore config
    if [ -f "/tmp/net.reidemeister.autorun/config" ]
    then
        cp /tmp/net.reidemeister.autorun/config /var/packages/autorun/target/
    fi

    # restore log
    if [ -f "/tmp/net.reidemeister.autorun/log" ]
    then
        cp /tmp/net.reidemeister.autorun/log /var/packages/autorun/target/
    fi

    echo "`date +%Y-%m-%d` `date +%H:%M:%S`: autorun upgraded<br/>" >> "/var/packages/autorun/target/log"
fi

# clean-up
rm -r /tmp/net.reidemeister.autorun

exit 0
