#!/bin/sh

DSMMAJOR=`/bin/get_key_value /etc.defaults/VERSION majorversion`
if [ $DSMMAJOR -lt 6 ]; then
	echo "This package can only be used in DSM 6.0 and above!" > $SYNOPKG_TEMP_LOGFILE
	exit 1
fi

exit 0
