#!/bin/sh

#clean-up temp when required
if [ -d "/tmp/net.reidemeister.autorun" ]
then
    rm -r /tmp/net.reidemeister.autorun
fi

# create temp
mkdir /tmp/net.reidemeister.autorun

# save config
cp /var/packages/autorun/target/config /tmp/net.reidemeister.autorun

# save log
cp /var/packages/autorun/target/log /tmp/net.reidemeister.autorun

exit 0
