#!/bin/sh

eval $(env | grep "^SYNOPKG_PKGDEST=")
eval $(env | grep "^config_script=")
eval $(env | grep "^config_search=")
eval $(env | grep "^config_wait=")
eval $(env | grep "^config_beep=")
eval $(env | grep "^config_led=")
eval $(env | grep "^config_key=")

echo "SCRIPT=$config_script" > "$SYNOPKG_PKGDEST/config"
echo "TRIES=$config_search" >> "$SYNOPKG_PKGDEST/config"
echo "WAIT=$config_wait" >> "$SYNOPKG_PKGDEST/config"
echo "KEY='$config_key'" >> "$SYNOPKG_PKGDEST/config"

if [ $config_beep = "true" ]
then
	echo "BEEP=1" >> "$SYNOPKG_PKGDEST/config"
else
	echo "BEEP=0" >> "$SYNOPKG_PKGDEST/config"
fi
if [ $config_led = "true" ]
then
	echo "LED=1" >> "$SYNOPKG_PKGDEST/config"
else
	echo "LED=0" >> "$SYNOPKG_PKGDEST/config"
fi

chmod 600 "$SYNOPKG_PKGDEST/config"

echo "`date +%Y-%m-%d` `date +%H:%M:%S`: autorun installed<br/>" >> "${SYNOPKG_PKGDEST}/log"

exit 0
