#!/bin/sh

case $1 in
	start)
		if [ -f /usr/lib/udev/rules.d/99-autorun.rules ]
		then
			exit 1
		else
			cp /var/packages/autorun/target/rules /usr/lib/udev/rules.d/99-autorun.rules
			chmod 400 /usr/lib/udev/rules.d/99-autorun.rules
			/usr/bin/udevadm control --reload-rules
		fi
                echo "`date +%Y-%m-%d` `date +%H:%M:%S`: autorun activated<br/>" >> /var/packages/autorun/target/log
		exit 0
	;;
	stop)
		if [ -f /usr/lib/udev/rules.d/99-autorun.rules ]
		then
			rm -f /usr/lib/udev/rules.d/99-autorun.rules
			/usr/bin/udevadm control --reload-rules
		fi

		echo "`date +%Y-%m-%d` `date +%H:%M:%S`: autorun deactivated<br/>" >> /var/packages/autorun/target/log
		exit 0
	;;
	status)
		if [ -f /usr/lib/udev/rules.d/99-autorun.rules ]
		then 
			exit 0
		else
			exit 1
		fi
	;;
esac
